version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      # Auth AWS
      - echo Authenticating into AWS ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 040133161491.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building Frontend Image
      - docker build -t overrice-website -f ./Dockerfile ./

      # Tag docker images
      - echo Tagging [Backend, Frontend] image...
      - docker tag overrice-website:latest 040133161491.dkr.ecr.us-east-1.amazonaws.com/overrice-website:latest

  post_build:
    commands:
      - echo Pushing Frontend image...
      - docker push 040133161491.dkr.ecr.us-east-1.amazonaws.com/overrice-website:latest

artifacts:
  files:
    - imagedefinitions.json